In [2]:
import pandas as pd

In [3]:
df=pd.read_csv('premier-player-23-24.csv')
df.head(5)

,Player,Nation,Pos,Age,MP,Starts,Min,90s,Gls,Ast,...,Ast_90,G+A_90,G-PK_90,G+A-PK_90,xG_90,xAG_90,xG+xAG_90,npxG_90,npxG+xAG_90,Team
0,Rodri,es ESP,MF,27.0,34,34,2931.0,32.6,8.0,9.0,...,0.28,0.52,0.25,0.52,0.12,0.12,0.24,0.12,0.24,Manchester City
1,Phil Foden,eng ENG,"FW,MF",23.0,35,33,2857.0,31.7,19.0,8.0,...,0.25,0.85,0.60,0.85,0.33,0.26,0.59,0.33,0.59,Manchester City
2,Ederson,br BRA,GK,29.0,33,33,2785.0,30.9,0.0,0.0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,Manchester City
3,Julián Álvarez,ar ARG,"MF,FW",23.0,36,31,2647.0,29.4,11.0,8.0,...,0.27,0.65,0.31,0.58,0.44,0.22,0.66,0.39,0.61,Manchester City
4,Kyle Walker,eng ENG,DF,33.0,32,30,2767.0,30.7,0.0,4.0,...,0.13,0.13,0.00,0.13,0.01,0.09,0.10,0.01,0.10,Manchester City

In [4]:
df2=pd.read_csv('players.csv')
df2.head()

,id,name,now_cost,position,team,web_name,transfers_in_event,influence_rank_type,news_added,ict_index_rank_type,...,now_cost_rank_type,ict_index,now_cost_rank,minutes,yellow_cards,cost_change_event_fall,red_cards,value_form,ict_index_rank,total_points
0,1,Folarin Balogun,44,FWD,Arsenal,Balogun,0,61,2023-08-31T08:55:15.272751Z,63,...,94,0.0,528,0,0,0,0,0.0,628,0
1,2,Cédric Alves Soares,39,DEF,Arsenal,Cédric,433,173,NaN,172,...,231,0.0,729,0,0,0,0,0.0,493,0
2,3,Mohamed Elneny,44,MID,Arsenal,M.Elneny,54,215,2023-12-12T22:30:08.433665Z,214,...,290,0.4,498,1,0,0,0,0.0,470,4
3,4,Fábio Ferreira Vieira,54,MID,Arsenal,Fábio Vieira,5,134,2023-12-07T12:00:08.489004Z,139,...,80,21.9,127,236,0,0,1,0.0,300,21
4,5,Gabriel dos Santos Magalhães,49,DEF,Arsenal,Gabriel,104278,42,2023-09-30T23:00:07.672676Z,47,...,31,43.3,247,1284,1,0,0,0.9,172,56

In [13]:
city1=df[df['Team']=='Manchester City']
city1

,Player,Nation,Pos,Age,MP,Starts,Min,90s,Gls,Ast,...,Ast_90,G+A_90,G-PK_90,G+A-PK_90,xG_90,xAG_90,xG+xAG_90,npxG_90,npxG+xAG_90,Team
0,Rodri,es ESP,MF,27.0,34,34,2931.0,32.6,8.0,9.0,...,0.28,0.52,0.25,0.52,0.12,0.12,0.24,0.12,0.24,Manchester City
1,Phil Foden,eng ENG,"FW,MF",23.0,35,33,2857.0,31.7,19.0,8.0,...,0.25,0.85,0.60,0.85,0.33,0.26,0.59,0.33,0.59,Manchester City
2,Ederson,br BRA,GK,29.0,33,33,2785.0,30.9,0.0,0.0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,Manchester City
3,Julián Álvarez,ar ARG,"MF,FW",23.0,36,31,2647.0,29.4,11.0,8.0,...,0.27,0.65,0.31,0.58,0.44,0.22,0.66,0.39,0.61,Manchester City
4,Kyle Walker,eng ENG,DF,33.0,32,30,2767.0,30.7,0.0,4.0,...,0.13,0.13,0.00,0.13,0.01,0.09,0.10,0.01,0.10,Manchester City
5,Bernardo Silva,pt POR,"MF,FW",28.0,33,29,2578.0,28.6,6.0,9.0,...,0.31,0.52,0.21,0.52,0.13,0.27,0.40,0.13,0.40,Manchester City
6,Erling Haaland,no NOR,FW,23.0,31,29,2552.0,28.4,27.0,5.0,...,0.18,1.13,0.71,0.88,1.03,0.15,1.18,0.81,0.96,Manchester City
7,Rúben Dias,pt POR,DF,26.0,30,28,2559.0,28.4,0.0,0.0,...,0.00,0.00,0.00,0.00,0.05,0.01,0.06,0.05,0.06,Manchester City
8,Manuel Akanji,ch SUI,"DF,MF",28.0,30,28,2511.0,27.9,2.0,0.0,...,0.00,0.07,0.07,0.07,0.07,0.02,0.09,0.07,0.09,Manchester City
9,Joško Gvardiol,hr CRO,DF,21.0,28,26,2328.0,25.9,4.0,1.0,...,0.04,0.19,0.15,0.19,0.12,0.06,0.18,0.12,0.18,Manchester City
10,Nathan Aké,nl NED,DF,28.0,29,24,2042.0,22.7,2.0,2.0,...,0.09,0.18,0.09,0.18,0.11,0.05,0.16,0.11,0.16,Manchester City
11,Jeremy Doku,be BEL,"FW,MF",21.0,29,18,1595.0,17.7,3.0,8.0,...,0.45,0.62,0.17,0.62,0.14,0.26,0.40,0.14,0.40,Manchester City
12,Mateo Kovačić,hr CRO,MF,29.0,30,16,1551.0,17.2,1.0,0.0,...,0.00,0.06,0.06,0.06,0.07,0.09,0.17,0.07,0.17,Manchester City
13,Kevin De Bruyne,be BEL,MF,32.0,18,15,1221.0,13.6,4.0,10.0,...,0.74,1.03,0.29,1.03,0.18,0.85,1.03,0.18,1.03,Manchester City
14,John Stones,eng ENG,"DF,MF",29.0,16,12,1064.0,11.8,1.0,0.0,...,0.00,0.08,0.08,0.08,0.09,0.02,0.11,0.09,0.11,Manchester City
15,Jack Grealish,eng ENG,"FW,MF",27.0,20,10,1009.0,11.2,3.0,1.0,...,0.09,0.36,0.27,0.36,0.19,0.22,0.41,0.19,0.41,Manchester City
16,Rico Lewis,eng ENG,"DF,MF",18.0,16,8,809.0,9.0,2.0,0.0,...,0.00,0.22,0.22,0.22,0.07,0.12,0.19,0.07,0.19,Manchester City
17,Matheus Nunes,pt POR,MF,24.0,17,7,661.0,7.3,0.0,2.0,...,0.27,0.27,0.00,0.27,0.11,0.15,0.27,0.11,0.27,Manchester City
18,Stefan Ortega,de GER,GK,30.0,9,5,635.0,7.1,0.0,0.0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,Manchester City
19,Oscar Bobb,no NOR,"FW,MF",20.0,14,2,302.0,3.4,1.0,1.0,...,0.30,0.60,0.30,0.60,0.41,0.37,0.78,0.41,0.78,Manchester City
20,Kalvin Phillips,eng ENG,MF,27.0,4,0,93.0,1.0,0.0,0.0,...,0.00,0.00,0.00,0.00,0.07,0.00,0.07,0.07,0.07,Manchester City
21,Sergio Gómez,es ESP,"FW,MF",22.0,6,0,53.0,0.6,0.0,1.0,...,1.70,1.70,0.00,1.70,0.41,0.31,0.73,0.41,0.73,Manchester City
22,Aymeric Laporte,es ESP,DF,29.0,1,0,12.0,0.1,0.0,0.0,...,0.00,0.00,0.00,0.00,0.27,0.00,0.27,0.27,0.27,Manchester City
23,Cole Palmer,eng ENG,MF,21.0,1,0,11.0,0.1,0.0,0.0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,Manchester City
24,James Mcatee,eng ENG,MF,20.0,1,0,1.0,0.0,0.0,0.0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,Manchester City

In [16]:
city2=df2[df2['team']=='Man City']
city2

,id,name,now_cost,position,team,web_name,transfers_in_event,influence_rank_type,news_added,ict_index_rank_type,...,now_cost_rank_type,ict_index,now_cost_rank,minutes,yellow_cards,cost_change_event_fall,red_cards,value_form,ict_index_rank,total_points
461,341,Manuel Akanji,49,DEF,Man City,Akanji,6343,48,2023-11-08T09:00:09.507801Z,46,...,29,44.3,241,1081,1,0,1,0.2,170,42
462,342,Nathan Aké,50,DEF,Man City,Aké,11485,56,2023-11-13T01:00:09.634159Z,39,...,21,46.5,177,825,0,0,0,0.2,156,43
463,343,Julián Álvarez,68,FWD,Man City,J.Alvarez,127990,5,NaN,4,...,15,128.0,39,1409,2,1,0,0.5,12,82
464,344,Bernardo Veiga de Carvalho e Silva,64,MID,Man City,Bernardo,21364,13,2023-09-20T09:00:09.855543Z,19,...,31,105.2,52,1178,3,0,0,0.6,28,65
465,345,Oscar Bobb,44,MID,Man City,Bobb,152,177,NaN,181,...,309,8.3,551,69,0,0,0,0.0,392,11
466,346,João Cancelo,58,DEF,Man City,Cancelo,0,249,2023-09-01T21:47:31.722632Z,249,...,5,0.0,71,0,0,0,0,0.0,761,0
467,347,Scott Carson,39,GKP,Man City,Carson,29,36,NaN,36,...,65,0.0,726,0,0,0,0,0.0,491,0
468,348,Shea Charles,45,MID,Man City,Charles,0,265,2023-07-11T09:00:10.230763Z,268,...,243,0.0,420,0,0,0,0,0.0,675,0
469,349,Kevin De Bruyne,102,MID,Man City,De Bruyne,8778,213,2023-08-12T08:00:06.610027Z,206,...,2,2.2,4,22,0,0,0,0.0,450,1
470,350,Rúben Gato Alves Dias,55,DEF,Man City,Rúben,7445,38,NaN,36,...,8,48.6,100,1275,0,0,0,0.3,146,35
471,352,Ederson Santana de Moraes,55,GKP,Man City,Ederson M.,10848,16,2023-12-15T18:00:10.673601Z,16,...,2,29.3,97,1440,3,0,0,0.3,242,46
472,353,Phil Foden,76,MID,Man City,Foden,56410,18,NaN,9,...,12,122.7,19,1334,1,0,0,0.6,14,76
473,354,Jack Grealish,72,MID,Man City,Grealish,13331,73,2023-12-15T18:00:10.702008Z,71,...,15,57.0,26,543,4,0,0,0.8,118,37
474,355,Erling Haaland,139,FWD,Man City,Haaland,66014,1,2023-12-10T18:00:10.148960Z,1,...,1,159.8,1,1294,1,0,0,0.2,3,112
475,356,Mateo Kovačić,47,MID,Man City,Kovačić,324,131,2023-11-14T11:30:09.729876Z,126,...,199,26.1,308,667,2,0,0,0.2,268,21
476,357,Aymeric Laporte,49,DEF,Man City,Laporte,0,159,2023-08-25T08:36:39.711991Z,155,...,25,2.9,223,11,0,0,0,0.0,441,1
477,358,Rico Lewis,43,DEF,Man City,R.Lewis,4233,131,NaN,119,...,152,17.4,607,340,1,0,0,0.8,326,29
478,359,Riyad Mahrez,75,MID,Man City,Mahrez,0,334,2023-07-31T07:05:47.120993Z,334,...,13,0.0,21,0,0,0,0,0.0,767,0
479,361,Stefan Ortega Moreno,38,GKP,Man City,Ortega Moreno,3134,32,NaN,32,...,87,1.9,768,90,0,1,0,0.0,452,2
480,363,Máximo Perrone,44,MID,Man City,Perrone,0,242,2023-08-25T08:39:41.545276Z,245,...,310,0.0,553,0,0,0,0,0.0,638,0
481,364,Kalvin Phillips,47,MID,Man City,Phillips,29,191,NaN,200,...,202,3.1,313,89,0,0,0,0.0,436,4
482,365,Rodrigo Hernandez,56,MID,Man City,Rodrigo,2226,16,2023-12-23T22:30:09.724645Z,30,...,57,87.1,92,1180,6,0,1,0.2,42,51
483,366,Sergio Gómez,39,DEF,Man City,Sergio Gómez,1661,152,2023-11-04T21:00:08.878260Z,150,...,244,3.8,759,15,0,0,0,0.0,423,5
484,367,Zack Steffen,39,GKP,Man City,Steffen,50,44,NaN,44,...,76,0.0,744,0,0,0,0,0.0,503,0
485,368,John Stones,53,DEF,Man City,Stones,3498,138,2023-11-08T09:00:09.561253Z,136,...,12,10.7,135,368,1,0,0,0.2,371,18
486,369,Kyle Walker,53,DEF,Man City,Walker,39585,53,NaN,17,...,11,59.7,132,1530,1,0,0,0.3,105,51
487,566,Matheus Luiz Nunes,48,MID,Man City,Matheus N.,106,133,2023-11-16T15:00:10.183986Z,143,...,196,19.0,300,408,0,0,1,0.1,317,13
488,616,Joško Gvardiol,48,DEF,Man City,Gvardiol,5918,69,NaN,44,...,35,44.8,301,1065,2,0,0,0.3,166,32
489,678,Jérémy Doku,65,MID,Man City,Doku,1468,39,2023-12-03T23:30:11.101545Z,32,...,28,86.4,47,693,2,0,0,0.0,44,49
490,762,Mahamadou Susoho,45,MID,Man City,Susoho,17,276,NaN,279,...,257,0.0,440,0,0,0,0,0.0,692,0