In [99]:
import pandas as pd

In [100]:
df=pd.read_csv('premier-player-23-24.csv')
df.head(5)

,Player,Nation,Pos,Age,MP,Starts,Min,90s,Gls,Ast,...,Ast_90,G+A_90,G-PK_90,G+A-PK_90,xG_90,xAG_90,xG+xAG_90,npxG_90,npxG+xAG_90,Team
0,Rodri,es ESP,MF,27.0,34,34,2931.0,32.6,8.0,9.0,...,0.28,0.52,0.25,0.52,0.12,0.12,0.24,0.12,0.24,Manchester City
1,Phil Foden,eng ENG,"FW,MF",23.0,35,33,2857.0,31.7,19.0,8.0,...,0.25,0.85,0.60,0.85,0.33,0.26,0.59,0.33,0.59,Manchester City
2,Ederson,br BRA,GK,29.0,33,33,2785.0,30.9,0.0,0.0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,Manchester City
3,Julián Álvarez,ar ARG,"MF,FW",23.0,36,31,2647.0,29.4,11.0,8.0,...,0.27,0.65,0.31,0.58,0.44,0.22,0.66,0.39,0.61,Manchester City
4,Kyle Walker,eng ENG,DF,33.0,32,30,2767.0,30.7,0.0,4.0,...,0.13,0.13,0.00,0.13,0.01,0.09,0.10,0.01,0.10,Manchester City

In [101]:
df2=pd.read_csv('players.csv')
df2.head()

,id,name,now_cost,position,team,web_name,transfers_in_event,influence_rank_type,news_added,ict_index_rank_type,...,now_cost_rank_type,ict_index,now_cost_rank,minutes,yellow_cards,cost_change_event_fall,red_cards,value_form,ict_index_rank,total_points
0,1,Folarin Balogun,44,FWD,Arsenal,Balogun,0,61,2023-08-31T08:55:15.272751Z,63,...,94,0.0,528,0,0,0,0,0.0,628,0
1,2,Cédric Alves Soares,39,DEF,Arsenal,Cédric,433,173,NaN,172,...,231,0.0,729,0,0,0,0,0.0,493,0
2,3,Mohamed Elneny,44,MID,Arsenal,M.Elneny,54,215,2023-12-12T22:30:08.433665Z,214,...,290,0.4,498,1,0,0,0,0.0,470,4
3,4,Fábio Ferreira Vieira,54,MID,Arsenal,Fábio Vieira,5,134,2023-12-07T12:00:08.489004Z,139,...,80,21.9,127,236,0,0,1,0.0,300,21
4,5,Gabriel dos Santos Magalhães,49,DEF,Arsenal,Gabriel,104278,42,2023-09-30T23:00:07.672676Z,47,...,31,43.3,247,1284,1,0,0,0.9,172,56

In [102]:
city1=df[df['Team']=='Manchester City']
city1

,Player,Nation,Pos,Age,MP,Starts,Min,90s,Gls,Ast,...,Ast_90,G+A_90,G-PK_90,G+A-PK_90,xG_90,xAG_90,xG+xAG_90,npxG_90,npxG+xAG_90,Team
0,Rodri,es ESP,MF,27.0,34,34,2931.0,32.6,8.0,9.0,...,0.28,0.52,0.25,0.52,0.12,0.12,0.24,0.12,0.24,Manchester City
1,Phil Foden,eng ENG,"FW,MF",23.0,35,33,2857.0,31.7,19.0,8.0,...,0.25,0.85,0.60,0.85,0.33,0.26,0.59,0.33,0.59,Manchester City
2,Ederson,br BRA,GK,29.0,33,33,2785.0,30.9,0.0,0.0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,Manchester City
3,Julián Álvarez,ar ARG,"MF,FW",23.0,36,31,2647.0,29.4,11.0,8.0,...,0.27,0.65,0.31,0.58,0.44,0.22,0.66,0.39,0.61,Manchester City
4,Kyle Walker,eng ENG,DF,33.0,32,30,2767.0,30.7,0.0,4.0,...,0.13,0.13,0.00,0.13,0.01,0.09,0.10,0.01,0.10,Manchester City
5,Bernardo Silva,pt POR,"MF,FW",28.0,33,29,2578.0,28.6,6.0,9.0,...,0.31,0.52,0.21,0.52,0.13,0.27,0.40,0.13,0.40,Manchester City
6,Erling Haaland,no NOR,FW,23.0,31,29,2552.0,28.4,27.0,5.0,...,0.18,1.13,0.71,0.88,1.03,0.15,1.18,0.81,0.96,Manchester City
7,Rúben Dias,pt POR,DF,26.0,30,28,2559.0,28.4,0.0,0.0,...,0.00,0.00,0.00,0.00,0.05,0.01,0.06,0.05,0.06,Manchester City
8,Manuel Akanji,ch SUI,"DF,MF",28.0,30,28,2511.0,27.9,2.0,0.0,...,0.00,0.07,0.07,0.07,0.07,0.02,0.09,0.07,0.09,Manchester City
9,Joško Gvardiol,hr CRO,DF,21.0,28,26,2328.0,25.9,4.0,1.0,...,0.04,0.19,0.15,0.19,0.12,0.06,0.18,0.12,0.18,Manchester City
10,Nathan Aké,nl NED,DF,28.0,29,24,2042.0,22.7,2.0,2.0,...,0.09,0.18,0.09,0.18,0.11,0.05,0.16,0.11,0.16,Manchester City
11,Jeremy Doku,be BEL,"FW,MF",21.0,29,18,1595.0,17.7,3.0,8.0,...,0.45,0.62,0.17,0.62,0.14,0.26,0.40,0.14,0.40,Manchester City
12,Mateo Kovačić,hr CRO,MF,29.0,30,16,1551.0,17.2,1.0,0.0,...,0.00,0.06,0.06,0.06,0.07,0.09,0.17,0.07,0.17,Manchester City
13,Kevin De Bruyne,be BEL,MF,32.0,18,15,1221.0,13.6,4.0,10.0,...,0.74,1.03,0.29,1.03,0.18,0.85,1.03,0.18,1.03,Manchester City
14,John Stones,eng ENG,"DF,MF",29.0,16,12,1064.0,11.8,1.0,0.0,...,0.00,0.08,0.08,0.08,0.09,0.02,0.11,0.09,0.11,Manchester City
15,Jack Grealish,eng ENG,"FW,MF",27.0,20,10,1009.0,11.2,3.0,1.0,...,0.09,0.36,0.27,0.36,0.19,0.22,0.41,0.19,0.41,Manchester City
16,Rico Lewis,eng ENG,"DF,MF",18.0,16,8,809.0,9.0,2.0,0.0,...,0.00,0.22,0.22,0.22,0.07,0.12,0.19,0.07,0.19,Manchester City
17,Matheus Nunes,pt POR,MF,24.0,17,7,661.0,7.3,0.0,2.0,...,0.27,0.27,0.00,0.27,0.11,0.15,0.27,0.11,0.27,Manchester City
18,Stefan Ortega,de GER,GK,30.0,9,5,635.0,7.1,0.0,0.0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,Manchester City
19,Oscar Bobb,no NOR,"FW,MF",20.0,14,2,302.0,3.4,1.0,1.0,...,0.30,0.60,0.30,0.60,0.41,0.37,0.78,0.41,0.78,Manchester City
20,Kalvin Phillips,eng ENG,MF,27.0,4,0,93.0,1.0,0.0,0.0,...,0.00,0.00,0.00,0.00,0.07,0.00,0.07,0.07,0.07,Manchester City
21,Sergio Gómez,es ESP,"FW,MF",22.0,6,0,53.0,0.6,0.0,1.0,...,1.70,1.70,0.00,1.70,0.41,0.31,0.73,0.41,0.73,Manchester City
22,Aymeric Laporte,es ESP,DF,29.0,1,0,12.0,0.1,0.0,0.0,...,0.00,0.00,0.00,0.00,0.27,0.00,0.27,0.27,0.27,Manchester City
23,Cole Palmer,eng ENG,MF,21.0,1,0,11.0,0.1,0.0,0.0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,Manchester City
24,James Mcatee,eng ENG,MF,20.0,1,0,1.0,0.0,0.0,0.0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,Manchester City

In [103]:
city2=df2.loc[df2['team']=='Man City',['name', 'now_cost','web_name']]

In [104]:
# Create a new column 'final_name' starting with the 'name' column
city2['final_name'] = city2['name']

# Manually swap for specific players
city2.loc[city2['name'] == 'Bernardo Veiga de Carvalho e Silva', 'final_name'] = city2['web_name']
city2.loc[city2['name'] == 'Rodrigo Hernandez', 'final_name'] = city2['web_name']
city2.loc[city2['name'] == 'Rúben Gato Alves Dias', 'final_name'] = city2['web_name']
city2.loc[city2['name'] == 'Ederson Santana de Moraes', 'final_name'] = city2['web_name']
city2.loc[city2['name'] == 'Stefan Ortega Moreno', 'final_name'] = city2['web_name']
city2.loc[city2['name'] == 'Matheus Luiz Nunes', 'final_name'] = city2['web_name']

In [105]:
city_2f=city2.loc[df2['team']=='Man City',['final_name', 'now_cost']]
city_2f.rename(columns={'final_name':'Player'}, inplace=True)

In [106]:
city_final=city1.merge(city_2f, on='Player', how='inner')
city_final

,Player,Nation,Pos,Age,MP,Starts,Min,90s,Gls,Ast,...,G+A_90,G-PK_90,G+A-PK_90,xG_90,xAG_90,xG+xAG_90,npxG_90,npxG+xAG_90,Team,now_cost
0,Rodri,es ESP,MF,27.0,34,34,2931.0,32.6,8.0,9.0,...,0.52,0.25,0.52,0.12,0.12,0.24,0.12,0.24,Manchester City,56
1,Phil Foden,eng ENG,"FW,MF",23.0,35,33,2857.0,31.7,19.0,8.0,...,0.85,0.60,0.85,0.33,0.26,0.59,0.33,0.59,Manchester City,76
2,Ederson,br BRA,GK,29.0,33,33,2785.0,30.9,0.0,0.0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,Manchester City,55
3,Julián Álvarez,ar ARG,"MF,FW",23.0,36,31,2647.0,29.4,11.0,8.0,...,0.65,0.31,0.58,0.44,0.22,0.66,0.39,0.61,Manchester City,68
4,Kyle Walker,eng ENG,DF,33.0,32,30,2767.0,30.7,0.0,4.0,...,0.13,0.00,0.13,0.01,0.09,0.10,0.01,0.10,Manchester City,53
5,Bernardo Silva,pt POR,"MF,FW",28.0,33,29,2578.0,28.6,6.0,9.0,...,0.52,0.21,0.52,0.13,0.27,0.40,0.13,0.40,Manchester City,64
6,Erling Haaland,no NOR,FW,23.0,31,29,2552.0,28.4,27.0,5.0,...,1.13,0.71,0.88,1.03,0.15,1.18,0.81,0.96,Manchester City,139
7,Rúben Dias,pt POR,DF,26.0,30,28,2559.0,28.4,0.0,0.0,...,0.00,0.00,0.00,0.05,0.01,0.06,0.05,0.06,Manchester City,55
8,Manuel Akanji,ch SUI,"DF,MF",28.0,30,28,2511.0,27.9,2.0,0.0,...,0.07,0.07,0.07,0.07,0.02,0.09,0.07,0.09,Manchester City,49
9,Joško Gvardiol,hr CRO,DF,21.0,28,26,2328.0,25.9,4.0,1.0,...,0.19,0.15,0.19,0.12,0.06,0.18,0.12,0.18,Manchester City,48
10,Nathan Aké,nl NED,DF,28.0,29,24,2042.0,22.7,2.0,2.0,...,0.18,0.09,0.18,0.11,0.05,0.16,0.11,0.16,Manchester City,50
11,Jeremy Doku,be BEL,"FW,MF",21.0,29,18,1595.0,17.7,3.0,8.0,...,0.62,0.17,0.62,0.14,0.26,0.40,0.14,0.40,Manchester City,65
12,Mateo Kovačić,hr CRO,MF,29.0,30,16,1551.0,17.2,1.0,0.0,...,0.06,0.06,0.06,0.07,0.09,0.17,0.07,0.17,Manchester City,47
13,Kevin De Bruyne,be BEL,MF,32.0,18,15,1221.0,13.6,4.0,10.0,...,1.03,0.29,1.03,0.18,0.85,1.03,0.18,1.03,Manchester City,102
14,John Stones,eng ENG,"DF,MF",29.0,16,12,1064.0,11.8,1.0,0.0,...,0.08,0.08,0.08,0.09,0.02,0.11,0.09,0.11,Manchester City,53
15,Jack Grealish,eng ENG,"FW,MF",27.0,20,10,1009.0,11.2,3.0,1.0,...,0.36,0.27,0.36,0.19,0.22,0.41,0.19,0.41,Manchester City,72
16,Rico Lewis,eng ENG,"DF,MF",18.0,16,8,809.0,9.0,2.0,0.0,...,0.22,0.22,0.22,0.07,0.12,0.19,0.07,0.19,Manchester City,43
17,Matheus Nunes,pt POR,MF,24.0,17,7,661.0,7.3,0.0,2.0,...,0.27,0.00,0.27,0.11,0.15,0.27,0.11,0.27,Manchester City,48
18,Stefan Ortega,de GER,GK,30.0,9,5,635.0,7.1,0.0,0.0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,Manchester City,38
19,Oscar Bobb,no NOR,"FW,MF",20.0,14,2,302.0,3.4,1.0,1.0,...,0.60,0.30,0.60,0.41,0.37,0.78,0.41,0.78,Manchester City,44
20,Kalvin Phillips,eng ENG,MF,27.0,4,0,93.0,1.0,0.0,0.0,...,0.00,0.00,0.00,0.07,0.00,0.07,0.07,0.07,Manchester City,47
21,Sergio Gómez,es ESP,"FW,MF",22.0,6,0,53.0,0.6,0.0,1.0,...,1.70,0.00,1.70,0.41,0.31,0.73,0.41,0.73,Manchester City,39
22,Aymeric Laporte,es ESP,DF,29.0,1,0,12.0,0.1,0.0,0.0,...,0.00,0.00,0.00,0.27,0.00,0.27,0.27,0.27,Manchester City,49

Cole Palmer and James Mcatee got excluded from our data

In [107]:
united1=df[df['Team']=='Manchester United']
united1

,Player,Nation,Pos,Age,MP,Starts,Min,90s,Gls,Ast,...,Ast_90,G+A_90,G-PK_90,G+A-PK_90,xG_90,xAG_90,xG+xAG_90,npxG_90,npxG+xAG_90,Team
173,André Onana,cm CMR,GK,27.0,38,38,3420.0,38.0,0.0,0.0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,Manchester United
174,Diogo Dalot,pt POR,DF,24.0,36,35,3174.0,35.3,2.0,3.0,...,0.09,0.14,0.06,0.14,0.05,0.08,0.13,0.05,0.13,Manchester United
175,Bruno Fernandes,pt POR,"MF,FW",28.0,35,35,3118.0,34.6,10.0,8.0,...,0.23,0.52,0.17,0.40,0.29,0.34,0.63,0.18,0.51,Manchester United
176,Alejandro Garnacho,ar ARG,FW,19.0,36,30,2565.0,28.5,7.0,4.0,...,0.14,0.39,0.25,0.39,0.29,0.18,0.47,0.29,0.47,Manchester United
177,Marcus Rashford,eng ENG,FW,25.0,33,26,2271.0,25.2,7.0,2.0,...,0.08,0.36,0.20,0.28,0.29,0.09,0.38,0.23,0.32,Manchester United
178,Rasmus Højlund,dk DEN,FW,20.0,30,25,2158.0,24.0,10.0,2.0,...,0.08,0.50,0.42,0.50,0.32,0.07,0.38,0.32,0.38,Manchester United
179,Casemiro,br BRA,"MF,DF",31.0,25,24,1982.0,22.0,1.0,2.0,...,0.09,0.14,0.05,0.14,0.16,0.05,0.20,0.16,0.20,Manchester United
180,Kobbie Mainoo,eng ENG,MF,18.0,24,24,1924.0,21.4,3.0,1.0,...,0.05,0.19,0.14,0.19,0.04,0.03,0.07,0.04,0.07,Manchester United
181,Aaron Wan-Bissaka,eng ENG,DF,25.0,22,20,1780.0,19.8,0.0,2.0,...,0.10,0.10,0.00,0.10,0.01,0.08,0.08,0.01,0.08,Manchester United
182,Scott McTominay,sct SCO,"MF,FW",26.0,32,18,1901.0,21.1,7.0,1.0,...,0.05,0.38,0.33,0.38,0.27,0.04,0.31,0.27,0.31,Manchester United
183,Harry Maguire,eng ENG,DF,30.0,22,18,1653.0,18.4,2.0,2.0,...,0.11,0.22,0.11,0.22,0.11,0.07,0.18,0.11,0.18,Manchester United
184,Raphaël Varane,fr FRA,DF,30.0,22,16,1375.0,15.3,1.0,0.0,...,0.00,0.07,0.07,0.07,0.08,0.00,0.09,0.08,0.09,Manchester United
185,Jonny Evans,nir NIR,DF,35.0,23,15,1392.0,15.5,0.0,1.0,...,0.06,0.06,0.00,0.06,0.00,0.08,0.08,0.00,0.08,Manchester United
186,Antony,br BRA,FW,23.0,29,15,1324.0,14.7,1.0,1.0,...,0.07,0.14,0.07,0.14,0.23,0.19,0.42,0.23,0.42,Manchester United
187,Victor Lindelöf,se SWE,DF,29.0,19,14,1328.0,14.8,1.0,1.0,...,0.07,0.14,0.07,0.14,0.05,0.02,0.07,0.05,0.07,Manchester United
188,Christian Eriksen,dk DEN,MF,31.0,22,12,1141.0,12.7,1.0,2.0,...,0.16,0.24,0.08,0.24,0.08,0.18,0.26,0.08,0.26,Manchester United
189,Luke Shaw,eng ENG,DF,28.0,12,12,959.0,10.7,0.0,0.0,...,0.00,0.00,0.00,0.00,0.00,0.09,0.10,0.00,0.10,Manchester United
190,Sofyan Amrabat,ma MAR,"MF,DF",26.0,21,10,938.0,10.4,0.0,0.0,...,0.00,0.00,0.00,0.00,0.01,0.03,0.04,0.01,0.04,Manchester United
191,Lisandro Martínez,ar ARG,DF,25.0,11,8,646.0,7.2,0.0,1.0,...,0.14,0.14,0.00,0.14,0.00,0.01,0.01,0.00,0.01,Manchester United
192,Mason Mount,eng ENG,"MF,FW",24.0,14,5,516.0,5.7,1.0,0.0,...,0.00,0.17,0.17,0.17,0.07,0.06,0.13,0.07,0.13,Manchester United
193,Anthony Martial,fr FRA,FW,27.0,13,5,448.0,5.0,1.0,0.0,...,0.00,0.20,0.20,0.20,0.25,0.05,0.29,0.25,0.29,Manchester United
194,Sergio Reguilón,es ESP,DF,26.0,9,4,412.0,4.6,0.0,0.0,...,0.00,0.00,0.00,0.00,0.04,0.16,0.20,0.04,0.20,Manchester United
195,Amad Diallo,ci CIV,"FW,MF",21.0,9,3,390.0,4.3,1.0,1.0,...,0.23,0.46,0.23,0.46,0.12,0.24,0.36,0.12,0.36,Manchester United
196,Willy Kambwala,fr FRA,DF,18.0,8,3,330.0,3.7,0.0,0.0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,Manchester United
197,Facundo Pellistri,uy URU,"FW,MF",21.0,9,1,172.0,1.9,0.0,1.0,...,0.52,0.52,0.00,0.52,0.38,0.05,0.43,0.38,0.43,Manchester United
198,Hannibal Mejbri,tn TUN,"MF,FW",20.0,5,1,133.0,1.5,1.0,0.0,...,0.00,0.68,0.68,0.68,0.02,0.25,0.27,0.02,0.27,Manchester United
199,Omari Forson,eng ENG,FW,19.0,4,1,70.0,0.8,0.0,1.0,...,1.29,1.29,0.00,1.29,0.04,0.23,0.27,0.04,0.27,Manchester United
200,Jadon Sancho,eng ENG,"FW,MF",23.0,3,0,79.0,0.9,0.0,0.0,...,0.00,0.00,0.00,0.00,0.00,0.06,0.06,0.00,0.06,Manchester United
201,Ethan Wheatley,eng ENG,FW,17.0,3,0,16.0,0.2,0.0,0.0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,Manchester United
202,Donny van de Beek,nl NED,DF,26.0,1,0,3.0,0.0,0.0,0.0,...,0.00,0.00,0.00,0.00,1.09,4.44,5.54,1.09,5.54,Manchester United
203,Daniel Gore,eng ENG,MF,18.0,1,0,1.0,0.0,0.0,0.0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,Manchester United

In [108]:
united2=df2.loc[df2['team']=='Man Utd',['name', 'now_cost','web_name']]

# Create a new column 'final_name' starting with the 'name' column
united2['final_name'] = united2['name']

# Manually swap for specific players
united2.loc[united2['name'] == 'Antony Matheus dos Santos', 'final_name'] = united2['web_name']
united2.loc[united2['name'] == 'Carlos Henrique Casimiro', 'final_name'] = united2['web_name']
united2.loc[united2['name'] == 'Bruno Borges Fernandes', 'final_name'] = united2['web_name']
united2.loc[united2['name'] == 'Diogo Dalot Teixeira', 'final_name'] = united2['web_name']
united2.loc[united2['name'] == 'Facundo Pellistri Rebollo', 'final_name'] = united2['web_name']

united2f=united2.loc[df2['team']=='Man Utd',['final_name', 'now_cost']]
united2f.rename(columns={'final_name':'Player'}, inplace=True)

In [109]:
united_final=united1.merge(united2f, on='Player', how='inner')
united_final

,Player,Nation,Pos,Age,MP,Starts,Min,90s,Gls,Ast,...,G+A_90,G-PK_90,G+A-PK_90,xG_90,xAG_90,xG+xAG_90,npxG_90,npxG+xAG_90,Team,now_cost
0,André Onana,cm CMR,GK,27.0,38,38,3420.0,38.0,0.0,0.0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,Manchester United,48
1,Diogo Dalot,pt POR,DF,24.0,36,35,3174.0,35.3,2.0,3.0,...,0.14,0.06,0.14,0.05,0.08,0.13,0.05,0.13,Manchester United,51
2,Bruno Fernandes,pt POR,"MF,FW",28.0,35,35,3118.0,34.6,10.0,8.0,...,0.52,0.17,0.40,0.29,0.34,0.63,0.18,0.51,Manchester United,82
3,Alejandro Garnacho,ar ARG,FW,19.0,36,30,2565.0,28.5,7.0,4.0,...,0.39,0.25,0.39,0.29,0.18,0.47,0.29,0.47,Manchester United,47
4,Marcus Rashford,eng ENG,FW,25.0,33,26,2271.0,25.2,7.0,2.0,...,0.36,0.20,0.28,0.29,0.09,0.38,0.23,0.32,Manchester United,85
5,Rasmus Højlund,dk DEN,FW,20.0,30,25,2158.0,24.0,10.0,2.0,...,0.50,0.42,0.50,0.32,0.07,0.38,0.32,0.38,Manchester United,68
6,Casemiro,br BRA,"MF,DF",31.0,25,24,1982.0,22.0,1.0,2.0,...,0.14,0.05,0.14,0.16,0.05,0.20,0.16,0.20,Manchester United,53
7,Kobbie Mainoo,eng ENG,MF,18.0,24,24,1924.0,21.4,3.0,1.0,...,0.19,0.14,0.19,0.04,0.03,0.07,0.04,0.07,Manchester United,44
8,Aaron Wan-Bissaka,eng ENG,DF,25.0,22,20,1780.0,19.8,0.0,2.0,...,0.10,0.00,0.10,0.01,0.08,0.08,0.01,0.08,Manchester United,44
9,Scott McTominay,sct SCO,"MF,FW",26.0,32,18,1901.0,21.1,7.0,1.0,...,0.38,0.33,0.38,0.27,0.04,0.31,0.27,0.31,Manchester United,49
10,Harry Maguire,eng ENG,DF,30.0,22,18,1653.0,18.4,2.0,2.0,...,0.22,0.11,0.22,0.11,0.07,0.18,0.11,0.18,Manchester United,42
11,Raphaël Varane,fr FRA,DF,30.0,22,16,1375.0,15.3,1.0,0.0,...,0.07,0.07,0.07,0.08,0.00,0.09,0.08,0.09,Manchester United,49
12,Jonny Evans,nir NIR,DF,35.0,23,15,1392.0,15.5,0.0,1.0,...,0.06,0.00,0.06,0.00,0.08,0.08,0.00,0.08,Manchester United,40
13,Antony,br BRA,FW,23.0,29,15,1324.0,14.7,1.0,1.0,...,0.14,0.07,0.14,0.23,0.19,0.42,0.23,0.42,Manchester United,68
14,Victor Lindelöf,se SWE,DF,29.0,19,14,1328.0,14.8,1.0,1.0,...,0.14,0.07,0.14,0.05,0.02,0.07,0.05,0.07,Manchester United,45
15,Christian Eriksen,dk DEN,MF,31.0,22,12,1141.0,12.7,1.0,2.0,...,0.24,0.08,0.24,0.08,0.18,0.26,0.08,0.26,Manchester United,58
16,Luke Shaw,eng ENG,DF,28.0,12,12,959.0,10.7,0.0,0.0,...,0.00,0.00,0.00,0.00,0.09,0.10,0.00,0.10,Manchester United,52
17,Sofyan Amrabat,ma MAR,"MF,DF",26.0,21,10,938.0,10.4,0.0,0.0,...,0.00,0.00,0.00,0.01,0.03,0.04,0.01,0.04,Manchester United,50
18,Lisandro Martínez,ar ARG,DF,25.0,11,8,646.0,7.2,0.0,1.0,...,0.14,0.00,0.14,0.00,0.01,0.01,0.00,0.01,Manchester United,47
19,Mason Mount,eng ENG,"MF,FW",24.0,14,5,516.0,5.7,1.0,0.0,...,0.17,0.17,0.17,0.07,0.06,0.13,0.07,0.13,Manchester United,68
20,Anthony Martial,fr FRA,FW,27.0,13,5,448.0,5.0,1.0,0.0,...,0.20,0.20,0.20,0.25,0.05,0.29,0.25,0.29,Manchester United,64
21,Sergio Reguilón,es ESP,DF,26.0,9,4,412.0,4.6,0.0,0.0,...,0.00,0.00,0.00,0.04,0.16,0.20,0.04,0.20,Manchester United,44
22,Amad Diallo,ci CIV,"FW,MF",21.0,9,3,390.0,4.3,1.0,1.0,...,0.46,0.23,0.46,0.12,0.24,0.36,0.12,0.36,Manchester United,44
23,Willy Kambwala,fr FRA,DF,18.0,8,3,330.0,3.7,0.0,0.0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,Manchester United,40
24,Facundo Pellistri,uy URU,"FW,MF",21.0,9,1,172.0,1.9,0.0,1.0,...,0.52,0.00,0.52,0.38,0.05,0.43,0.38,0.43,Manchester United,43
25,Hannibal Mejbri,tn TUN,"MF,FW",20.0,5,1,133.0,1.5,1.0,0.0,...,0.68,0.68,0.68,0.02,0.25,0.27,0.02,0.27,Manchester United,44
26,Omari Forson,eng ENG,FW,19.0,4,1,70.0,0.8,0.0,1.0,...,1.29,0.00,1.29,0.04,0.23,0.27,0.04,0.27,Manchester United,44
27,Jadon Sancho,eng ENG,"FW,MF",23.0,3,0,79.0,0.9,0.0,0.0,...,0.00,0.00,0.00,0.00,0.06,0.06,0.00,0.06,Manchester United,67
28,Donny van de Beek,nl NED,DF,26.0,1,0,3.0,0.0,0.0,0.0,...,0.00,0.00,0.00,1.09,4.44,5.54,1.09,5.54,Manchester United,47
29,Daniel Gore,eng ENG,MF,18.0,1,0,1.0,0.0,0.0,0.0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,Manchester United,45

Álvaro Carreras got excluded from our dataset

In [112]:
palace1=df[df['Team']=='Crystal Palace']
palace1

,Player,Nation,Pos,Age,MP,Starts,Min,90s,Gls,Ast,...,Ast_90,G+A_90,G-PK_90,G+A-PK_90,xG_90,xAG_90,xG+xAG_90,npxG_90,npxG+xAG_90,Team
261,Joachim Andersen,dk DEN,DF,27.0,38,38,3415.0,37.9,2.0,3.0,...,0.08,0.13,0.05,0.13,0.04,0.07,0.12,0.04,0.12,Crystal Palace
262,Tyrick Mitchell,eng ENG,"DF,MF",23.0,37,37,3204.0,35.6,2.0,3.0,...,0.08,0.14,0.06,0.14,0.04,0.08,0.12,0.04,0.12,Crystal Palace
263,Jordan Ayew,gh GHA,"FW,MF",31.0,35,30,2543.0,28.3,4.0,7.0,...,0.25,0.39,0.14,0.39,0.14,0.15,0.29,0.14,0.29,Crystal Palace
264,Jefferson Lerma,co COL,"MF,DF",28.0,28,27,2400.0,26.7,1.0,1.0,...,0.04,0.07,0.04,0.07,0.10,0.08,0.18,0.10,0.18,Crystal Palace
265,Jean-Philippe Mateta,fr FRA,FW,26.0,35,25,2282.0,25.4,16.0,5.0,...,0.20,0.83,0.55,0.75,0.43,0.12,0.56,0.37,0.49,Crystal Palace
266,Eberechi Eze,eng ENG,"MF,FW",25.0,27,24,2055.0,22.8,11.0,4.0,...,0.18,0.66,0.44,0.61,0.40,0.23,0.62,0.36,0.59,Crystal Palace
267,Chris Richards,us USA,"DF,MF",23.0,26,23,2094.0,23.3,1.0,1.0,...,0.04,0.09,0.04,0.09,0.03,0.02,0.04,0.03,0.04,Crystal Palace
268,Marc Guéhi,eng ENG,DF,23.0,25,23,2021.0,22.5,0.0,1.0,...,0.04,0.04,0.00,0.04,0.03,0.03,0.05,0.03,0.05,Crystal Palace
269,Joel Ward,eng ENG,DF,33.0,26,23,1980.0,22.0,0.0,1.0,...,0.05,0.05,0.00,0.05,0.04,0.01,0.05,0.04,0.05,Crystal Palace
270,Will Hughes,eng ENG,MF,28.0,30,23,1891.0,21.0,0.0,1.0,...,0.05,0.05,0.00,0.05,0.02,0.05,0.07,0.02,0.07,Crystal Palace
271,Sam Johnstone,eng ENG,GK,30.0,20,20,1796.0,20.0,0.0,0.0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,Crystal Palace
272,Dean Henderson,eng ENG,GK,26.0,18,18,1620.0,18.0,0.0,0.0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,Crystal Palace
273,Odsonne Édouard,fr FRA,"FW,MF",25.0,30,17,1555.0,17.3,7.0,0.0,...,0.00,0.41,0.41,0.41,0.36,0.07,0.43,0.36,0.43,Crystal Palace
274,Jeffrey Schlupp,gh GHA,"FW,MF",30.0,29,17,1352.0,15.0,2.0,2.0,...,0.13,0.27,0.13,0.27,0.12,0.15,0.27,0.12,0.27,Crystal Palace
275,Daniel Muñoz,co COL,"DF,MF",27.0,16,16,1439.0,16.0,0.0,4.0,...,0.25,0.25,0.00,0.25,0.08,0.15,0.23,0.08,0.23,Crystal Palace
276,Adam Wharton,eng ENG,MF,19.0,16,15,1297.0,14.4,0.0,3.0,...,0.21,0.21,0.00,0.21,0.02,0.17,0.19,0.02,0.19,Crystal Palace
277,Nathaniel Clyne,eng ENG,DF,32.0,19,14,1338.0,14.9,0.0,0.0,...,0.00,0.00,0.00,0.00,0.01,0.01,0.03,0.01,0.03,Crystal Palace
278,Michael Olise,fr FRA,"FW,MF",21.0,19,14,1275.0,14.2,10.0,6.0,...,0.42,1.13,0.64,1.06,0.39,0.41,0.80,0.33,0.74,Crystal Palace
279,Cheick Doucouré,ml MLI,MF,23.0,11,11,919.0,10.2,0.0,0.0,...,0.00,0.00,0.00,0.00,0.03,0.07,0.10,0.03,0.10,Crystal Palace
280,Jaïro Riedewald,nl NED,"MF,FW",26.0,9,2,235.0,2.6,0.0,0.0,...,0.00,0.00,0.00,0.00,0.01,0.00,0.01,0.01,0.01,Crystal Palace
281,Matheus França,br BRA,"MF,FW",19.0,10,1,232.0,2.6,0.0,1.0,...,0.39,0.39,0.00,0.39,0.14,0.34,0.48,0.14,0.48,Crystal Palace
282,Naouirou Ahamada,fr FRA,"MF,FW",21.0,20,0,349.0,3.9,0.0,0.0,...,0.00,0.00,0.00,0.00,0.13,0.01,0.13,0.13,0.13,Crystal Palace
283,David Ozoh,eng ENG,"MF,DF",18.0,9,0,156.0,1.7,0.0,0.0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,Crystal Palace
284,Jesurun Rak Sakyi,eng ENG,"MF,FW",20.0,6,0,136.0,1.5,0.0,0.0,...,0.00,0.00,0.00,0.00,0.28,0.10,0.38,0.28,0.38,Crystal Palace
285,James Tomkins,eng ENG,DF,34.0,4,0,10.0,0.1,0.0,0.0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,Crystal Palace
286,Remi Matthews,eng ENG,GK,29.0,1,0,4.0,0.0,0.0,0.0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,Crystal Palace

In [116]:
palace2=df2.loc[df2['team']=='Crystal Palace',['name', 'now_cost','web_name']]

# Create a new column 'final_name' starting with the 'name' column
palace2['final_name'] = palace2['name']

# Manually swap for specific players
palace2.loc[palace2['name'] == 'Matheus França de Oliveira', 'final_name'] = palace2['web_name']


palace2f=palace2.loc[df2['team']=='Crystal Palace',['final_name', 'now_cost']]
palace2f.rename(columns={'final_name':'Player'}, inplace=True)

In [117]:
palace_final=palace1.merge(palace2f, on='Player', how='inner')
palace_final

,Player,Nation,Pos,Age,MP,Starts,Min,90s,Gls,Ast,...,G+A_90,G-PK_90,G+A-PK_90,xG_90,xAG_90,xG+xAG_90,npxG_90,npxG+xAG_90,Team,now_cost
0,Joachim Andersen,dk DEN,DF,27.0,38,38,3415.0,37.9,2.0,3.0,...,0.13,0.05,0.13,0.04,0.07,0.12,0.04,0.12,Crystal Palace,49
1,Tyrick Mitchell,eng ENG,"DF,MF",23.0,37,37,3204.0,35.6,2.0,3.0,...,0.14,0.06,0.14,0.04,0.08,0.12,0.04,0.12,Crystal Palace,47
2,Jordan Ayew,gh GHA,"FW,MF",31.0,35,30,2543.0,28.3,4.0,7.0,...,0.39,0.14,0.39,0.14,0.15,0.29,0.14,0.29,Crystal Palace,54
3,Jefferson Lerma,co COL,"MF,DF",28.0,28,27,2400.0,26.7,1.0,1.0,...,0.07,0.04,0.07,0.10,0.08,0.18,0.10,0.18,Crystal Palace,47
4,Jean-Philippe Mateta,fr FRA,FW,26.0,35,25,2282.0,25.4,16.0,5.0,...,0.83,0.55,0.75,0.43,0.12,0.56,0.37,0.49,Crystal Palace,49
5,Eberechi Eze,eng ENG,"MF,FW",25.0,27,24,2055.0,22.8,11.0,4.0,...,0.66,0.44,0.61,0.40,0.23,0.62,0.36,0.59,Crystal Palace,60
6,Chris Richards,us USA,"DF,MF",23.0,26,23,2094.0,23.3,1.0,1.0,...,0.09,0.04,0.09,0.03,0.02,0.04,0.03,0.04,Crystal Palace,39
7,Marc Guéhi,eng ENG,DF,23.0,25,23,2021.0,22.5,0.0,1.0,...,0.04,0.00,0.04,0.03,0.03,0.05,0.03,0.05,Crystal Palace,45
8,Joel Ward,eng ENG,DF,33.0,26,23,1980.0,22.0,0.0,1.0,...,0.05,0.00,0.05,0.04,0.01,0.05,0.04,0.05,Crystal Palace,45
9,Will Hughes,eng ENG,MF,28.0,30,23,1891.0,21.0,0.0,1.0,...,0.05,0.00,0.05,0.02,0.05,0.07,0.02,0.07,Crystal Palace,49
10,Sam Johnstone,eng ENG,GK,30.0,20,20,1796.0,20.0,0.0,0.0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,Crystal Palace,45
11,Dean Henderson,eng ENG,GK,26.0,18,18,1620.0,18.0,0.0,0.0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,Crystal Palace,44
12,Odsonne Édouard,fr FRA,"FW,MF",25.0,30,17,1555.0,17.3,7.0,0.0,...,0.41,0.41,0.41,0.36,0.07,0.43,0.36,0.43,Crystal Palace,54
13,Jeffrey Schlupp,gh GHA,"FW,MF",30.0,29,17,1352.0,15.0,2.0,2.0,...,0.27,0.13,0.27,0.12,0.15,0.27,0.12,0.27,Crystal Palace,49
14,Nathaniel Clyne,eng ENG,DF,32.0,19,14,1338.0,14.9,0.0,0.0,...,0.00,0.00,0.00,0.01,0.01,0.03,0.01,0.03,Crystal Palace,44
15,Michael Olise,fr FRA,"FW,MF",21.0,19,14,1275.0,14.2,10.0,6.0,...,1.13,0.64,1.06,0.39,0.41,0.80,0.33,0.74,Crystal Palace,58
16,Cheick Doucouré,ml MLI,MF,23.0,11,11,919.0,10.2,0.0,0.0,...,0.00,0.00,0.00,0.03,0.07,0.10,0.03,0.10,Crystal Palace,49
17,Jaïro Riedewald,nl NED,"MF,FW",26.0,9,2,235.0,2.6,0.0,0.0,...,0.00,0.00,0.00,0.01,0.00,0.01,0.01,0.01,Crystal Palace,44
18,Matheus França,br BRA,"MF,FW",19.0,10,1,232.0,2.6,0.0,1.0,...,0.39,0.00,0.39,0.14,0.34,0.48,0.14,0.48,Crystal Palace,49
19,Naouirou Ahamada,fr FRA,"MF,FW",21.0,20,0,349.0,3.9,0.0,0.0,...,0.00,0.00,0.00,0.13,0.01,0.13,0.13,0.13,Crystal Palace,43
20,David Ozoh,eng ENG,"MF,DF",18.0,9,0,156.0,1.7,0.0,0.0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,Crystal Palace,45
21,Jesurun Rak Sakyi,eng ENG,"MF,FW",20.0,6,0,136.0,1.5,0.0,0.0,...,0.00,0.00,0.00,0.28,0.10,0.38,0.28,0.38,Crystal Palace,45
22,James Tomkins,eng ENG,DF,34.0,4,0,10.0,0.1,0.0,0.0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,Crystal Palace,40
23,Remi Matthews,eng ENG,GK,29.0,1,0,4.0,0.0,0.0,0.0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,Crystal Palace,39

Lost Daniel Muñoz and Adam Wharton due to inexistant market value data